DOMAIN = "load_analyser"
CONF_NAME = "name"
CONF_POWER_SENSOR = "power_sensor"
CONF_ENERGY_SENSOR = "energy_sensor"
CONF_PROGRAM_SENSOR = "program_sensor"
CONF_STATE_SENSOR = "state_sensor"
CONF_TARIFF_SENSOR = "tariff_sensor"
CONF_GREEN_WINDOW_ENTITY = "green_window_entity"
CONF_BLOCKED_WINDOW_ENTITY = "blocked_window_entity"
CONF_EARLIEST_START_ENTITY = "earliest_start_entity"
CONF_LATEST_FINISH_ENTITY = "latest_finish_entity"
DEFAULT_SCAN_INTERVAL = 60
PLATFORMS = ["binary_sensor", "button", "sensor"]
